# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
